apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
  namespace: default
  labels:
    app: {{ .Values.app.name }}
    version: {{ $.Chart.AppVersion }}
    env: {{ .Values.env }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
        version: {{ $.Chart.AppVersion }}
    spec:
      containers:
        - name: {{ .Values.app.name }}
          image: vitorcvargas/financial-info-api:latest
          imagePullPolicy: {{ .Values.image.imagePullPolicy }}
          ports:
          - containerPort: 80