apiVersion: v1
kind: Service
metadata:
  name: financial-info-service
spec:
  type: NodePort
  selector:
    app: {{ .Values.app.name }}
  ports: 
    - port: 8080
      targetPort: 8080
      nodePort: 31515