apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-persistent-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

---

apiVersion: apps/v1
kind: Deployment                    
metadata:
  name: fin-info-mysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:                    
      app: {{ .Values.app.name }}
  strategy:
    type: Recreate
  template:                         
    metadata:
      labels:                       
        app: {{ .Values.app.name }}
    spec:
      volumes: 
      - name: {{ .Values.database.storage }}
        persistentVolumeClaim:
          claimName: database-persistent-volume-claim                    
      containers:
      - name: {{ .Values.app.name }}
        image: mysql:5.7         
        ports:
          - containerPort: 3306
        volumeMounts:
          - name: {{ .Values.database.storage }}
            mountPath: /var/lib/mysql
        env:                        
        - name: MYSQL_ROOT_PASSWORD 
          valueFrom:
            secretKeyRef:
              name: mysqlfininfopassword
              key: MYSQL_FIN_INFO_PASSWORD
        - name: MYSQL_DATABASE
          value: {{ .Values.database.name }}
        